create schema pteta;

--TODO: add UNIQUE constaint of (lat, lng, speed, orientation, gpstime, inDepo, vehicleId, response_datetime)
create table pteta.gpsdata (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lat" float,
  "lng" float,
  "speed" float,
  "orientation" float,
  "gpstime" TIMESTAMP,
  "inDepo" bool,
  "vehicleId" int,
  "response_datetime" TIMESTAMP with TIME ZONE,
  "edited" TIMESTAMP DEFAULT now()
);

--TODO: add UNIQUE constaint of (imei, name, busNumber, remark, perevId, routeId)
create table pteta.vehicle (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "imei" varchar,
  "name" varchar,
  "busNumber" int,
  "remark" varchar,
  "perevId" int,
  "routeId" int,
  "edited" TIMESTAMP with TIME ZONE DEFAULT now()
);

create table pteta.owner (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "perevName" varchar,
  "edited" TIMESTAMP with TIME ZONE DEFAULT now()
);

create table pteta.route (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "routeName" varchar,
  "routeColour" varchar,
  "edited" TIMESTAMP with TIME ZONE DEFAULT now()
);

alter TABLE pteta.gpsdata ADD FOREIGN KEY ("vehicleId") REFERENCES pteta.vehicle ("id");

alter TABLE pteta.vehicle ADD FOREIGN KEY ("perevId") REFERENCES pteta.owner ("id");

alter TABLE pteta.vehicle ADD FOREIGN KEY ("routeId") REFERENCES pteta.route ("id");
