--DROP SCHEMA IF EXISTS pteta_v2 CASCADE;

--DROP TABLE IF EXISTS "vehicle" CASCADE;
--DROP TABLE IF EXISTS "gpsdata" CASCADE;
--DROP TABLE IF EXISTS "route" CASCADE;
--DROP TABLE IF EXISTS "owner" CASCADE;

CREATE SCHEMA pteta_v2;

CREATE TABLE pteta_v2.gpsdata (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lat float NOT NULL,
  lng float NOT NULL,
  speed float NOT NULL,
  orientation float NOT NULL,
  gpstime TIMESTAMP NOT NULL,
  in_depo bool NOT NULL,
  vehicle_id int NOT NULL,
  route_id int NOT NULL,
  response_datetime TIMESTAMP with TIME ZONE,
  edited TIMESTAMP DEFAULT now(),
  UNIQUE(lat, lng, speed, orientation, gpstime, vehicle_id, route_id)
);

CREATE TABLE pteta_v2.vehicle(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  imei varchar NOT NULL,
  name varchar NOT NULL,
  bus_number varchar NOT NULL,
  remark varchar,
  perev_id int NOT NULL,
  edited TIMESTAMP with TIME ZONE DEFAULT now()
);

CREATE TABLE pteta_v2.owner (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perev_name varchar NOT NULL,
  edited TIMESTAMP with TIME ZONE DEFAULT now()
);

CREATE TABLE pteta_v2.route (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_name varchar NOT NULL,
  route_colour varchar,
  edited TIMESTAMP with TIME ZONE DEFAULT now()
);

ALTER TABLE pteta_v2.gpsdata ADD FOREIGN KEY (vehicle_id) REFERENCES pteta_v2.vehicle (id);

ALTER TABLE pteta_v2.gpsdata ADD FOREIGN KEY (route_id) REFERENCES pteta_v2.route (id);

ALTER TABLE pteta_v2.vehicle ADD FOREIGN KEY (perev_id) REFERENCES pteta_v2.owner (id);
