CREATE SCHEMA "pteta";

CREATE TABLE "pteta"."gpsdata" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lat" float,
  "lng" float,
  "speed" float,
  "orientation" float,
  "gpstime" datetime,
  "inDepo" bool,
  "routeId" int,
  "response_datetime" datetime,
  "edited" datetime,
  PRIMARY KEY ("id")
);

CREATE TABLE pteta.vehicle (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "imei" varchar,
  "name" varchar,
  "busNumber" int,
  "remark" varchar,
  "perevId" int,
  "routeId" int,
  "edited" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE "pteta"."owner" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "perevName" varchar,
  "edited" datetime,
  PRIMARY KEY ("id")
);

CREATE TABLE "pteta"."route" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "routeName" varchar,
  "routeColour" varchar,
  "etited" datetime,
  PRIMARY KEY ("id")
);

ALTER TABLE "pteta"."gpsdata"
ADD FOREIGN KEY ("routeId") REFERENCES "pteta"."vehicle" ("id");

ALTER TABLE "pteta"."vehicle" ADD FOREIGN KEY ("perevId") REFERENCES "pteta"."owner" ("id");

ALTER TABLE "pteta"."vehicle" ADD FOREIGN KEY ("routeId") REFERENCES "pteta"."route" ("id");
