name: Publish images

on:
  release: 
    types:[published]
  schedule: 
    - cron: "0 20 * * Sat"

env:
  DOCKER_IMAGE_NAME: pteta
  DOCKER_IMAGE_VERSION : latest
  DOCKER_IMAGE_FULL_NAME : ${{DOCKER_IMAGE_NAME}}:${{DOCKER_IMAGE_VERSION}}
  DOCKER_IMAGE_HUB_PATH : ${{ secrets.DOCKER_HUB_USERNAME }}/${{DOCKER_IMAGE_NAME}}:${{DOCKER_IMAGE_VERSION}}
  
jobs:
  update: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Get release version 
        id: get_version 
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Echo variables
        run: |
          echo DOCKER_IMAGE_NAME=${{DOCKER_IMAGE_NAME}}
          echo DOCKER_IMAGE_VERSION=${{DOCKER_IMAGE_VERSION}}
          echo DOCKER_IMAGE_FULL_NAME=${{DOCKER_IMAGE_FULL_NAME}}
          echo DOCKER_IMAGE_HUB_PATH=${{DOCKER_IMAGE_HUB_PATH}}
          echo RELEASE_VERSION=${{RELEASE_VERSION}}
    
